#include <gtest/gtest.h>
#include <fmt/core.h>
#include <nlohmann/json.hpp>
#include <string>
#include <vector>

// Using declarations for clean and readable code
using json = nlohmann::json;

/**
 * @brief Component under test: A helper class to format user data into a JSON string.
 */
class UserProfileFormatter {
 public:
    static std::string make_json_profile(const std::string& name, int age, const std::vector<std::string>& skills) {
        // Construct a modern JSON object using nlohmann/json
        json j;
        j["name"]   = name;
        j["age"]    = age;
        j["skills"] = skills;

        // Serialize JSON to string and format it with a header using fmt
        std::string json_str = j.dump();
        return fmt::format("[USER_DATA] {}", json_str);
    }
};

// ============================================================================
// UNIT TESTS USING GOOGLE TEST
// ============================================================================

/**
 * @test Verify that UserProfileFormatter correctly structures and formats user data.
 */
TEST(UserProfileFormatterTest, HandlesValidUserDataCorrectly) {
    // 1. ARRANGE: Set up the test inputs and expected values
    const std::string              input_name   = "Alice";
    const int                      input_age    = 25;
    const std::vector<std::string> input_skills = {"C++", "CMake", "Linux"};

    // 2. ACT: Execute the function under test
    std::string result = UserProfileFormatter::make_json_profile(input_name, input_age, input_skills);

    // 3. ASSERT: Validate the results using Google Test assertions
    // Check if the prefix generated by {fmt} is correct
    ASSERT_EQ(result.rfind("[USER_DATA] ", 0), 0) << "Result should start with [USER_DATA] prefix";

    // Extract the JSON substring to parse and verify its internal content
    std::string extracted_json = result.substr(12);  // Length of "[USER_DATA] " is 12

    // Parse it back to a JSON object to check fields safely
    json parsed_json = json::parse(extracted_json);

    EXPECT_EQ(parsed_json["name"].get<std::string>(), "Alice");
    EXPECT_EQ(parsed_json["age"].get<int>(), 25);
    EXPECT_EQ(parsed_json["skills"].size(), 3);
    EXPECT_EQ(parsed_json["skills"][0].get<std::string>(), "C++");
}

/**
 * @test Verify the JSON validation logic when handling empty data fields.
 */
TEST(UserProfileFormatterTest, HandlesEmptyFieldsGracefully) {
    // 1. ARRANGE
    const std::string              empty_name   = "";
    const int                      age          = 0;
    const std::vector<std::string> empty_skills = {};

    // 2. ACT
    std::string result = UserProfileFormatter::make_json_profile(empty_name, age, empty_skills);

    // 3. ASSERT
    std::string extracted_json = result.substr(12);
    json        parsed_json    = json::parse(extracted_json);

    EXPECT_TRUE(parsed_json["name"].get<std::string>().empty());
    EXPECT_EQ(parsed_json["age"].get<int>(), 0);
    EXPECT_TRUE(parsed_json["skills"].is_array());
    EXPECT_TRUE(parsed_json["skills"].empty());
}
#include "json_helper.h"

// ============================================================================
// FIXTURE CLASS FOR FILE I/O TESTS
// ============================================================================
/**
 * @brief Test fixture to manage temporary JSON files on the disk during testing.
 */
class JsonHelperFileTest : public ::testing::Test {
 protected:
    void SetUp() override {
        // Define paths for temporary test files
        test_valid_file   = "test_valid.json";
        test_invalid_file = "test_invalid.json";
        test_output_file  = "test_output.json";

        // Create a valid JSON file on disk
        std::ofstream valid_out(test_valid_file);
        valid_out << R"({"project": "GTest", "version": 1, "active": true})";
        valid_out.close();

        // Create a corrupted/invalid JSON file on disk
        std::ofstream invalid_out(test_invalid_file);
        invalid_out << R"({"project": "GTest", "version": )";  // Missing value and closing bracket
        invalid_out.close();
    }

    void TearDown() override {
        // Clean up all temporary files after tests run to prevent disk pollution
        // std::remove(test_valid_file.c_str());
        // std::remove(test_invalid_file.c_str());
        // std::remove(test_output_file.c_str());
    }

    std::string test_valid_file;
    std::string test_invalid_file;
    std::string test_output_file;
};

// ============================================================================
// 1. UNIT TESTS FOR FILE I/O OPERATIONS
// ============================================================================

/**
 * @test Verify successful loading of a valid JSON file and handling of invalid files.
 */
TEST_F(JsonHelperFileTest, LoadFromFileBehaviors) {
    nlohmann::json root;

    // Test case A: Valid file path and valid content
    bool load_success = JsonHelper::load_from_file(test_valid_file, root);
    ASSERT_TRUE(load_success) << "Should return true for valid files";
    EXPECT_EQ(root["project"].get<std::string>(), "GTest");

    // Test case B: Valid file path but corrupted JSON content
    bool load_corrupted = JsonHelper::load_from_file(test_invalid_file, root);
    EXPECT_FALSE(load_corrupted) << "Should return false for syntax errors in JSON";

    // Test case C: Non-existent file path
    bool load_missing = JsonHelper::load_from_file("ghost_file.json", root);
    EXPECT_FALSE(load_missing) << "Should return false if file does not exist";
}

/**
 * @test Verify saving JSON data to disk with and without prettification formatting.
 */
TEST_F(JsonHelperFileTest, SaveToFileBehaviors) {
    // Arrange
    nlohmann::json root_to_save;
    root_to_save["server"] = "localhost";
    root_to_save["port"]   = 8080;

    // Act: Save data to disk
    bool save_success = JsonHelper::save_to_file(test_output_file, root_to_save, true);

    // Assert
    ASSERT_TRUE(save_success) << "Should return true upon successful file write";

    // Reload the saved file to verify data integrity
    nlohmann::json reloaded_root;
    bool           reload_success = JsonHelper::load_from_file(test_output_file, reloaded_root);
    ASSERT_TRUE(reload_success);
    EXPECT_EQ(reloaded_root["server"].get<std::string>(), "localhost");
    EXPECT_EQ(reloaded_root["port"].get<int>(), 8080);
}

// ============================================================================
// 2. UNIT TESTS FOR SAFE DATA EXTRACTION
// ============================================================================

/**
 * @test Test safe string extraction behaviors including happy path, type mismatch, and missing keys.
 */
TEST(JsonHelperDataTest, GetStringBehaviors) {
    // Arrange
    nlohmann::json node = {{"name", "Ubuntu"},
                           {"code", 20},  // Type mismatch target (int instead of string)
                           {"status", true}};

    // Act & Assert
    // Scenario A: Happy path (Key exists and type matches)
    EXPECT_EQ(JsonHelper::get_string(node, "name", "unknown"), "Ubuntu");

    // Scenario B: Key is completely missing (Should return default value)
    EXPECT_EQ(JsonHelper::get_string(node, "architecture", "x86_64"), "x86_64");

    // Scenario C: Key exists but is an integer, not a string (Should fallback safely)
    EXPECT_EQ(JsonHelper::get_string(node, "code", "fallback"), "fallback");
}

/**
 * @test Test safe integer extraction behaviors.
 */
TEST(JsonHelperDataTest, GetIntBehaviors) {
    // Arrange
    nlohmann::json node = {
        {"age", 17}, {"weight", "70kg"}  // Type mismatch target
    };

    // Act & Assert
    EXPECT_EQ(JsonHelper::get_int(node, "age", 0), 17);
    EXPECT_EQ(JsonHelper::get_int(node, "height", 180), 180);  // Missing key
    EXPECT_EQ(JsonHelper::get_int(node, "weight", -1), -1);    // Type mismatch
}

/**
 * @test Test safe boolean extraction behaviors.
 */
TEST(JsonHelperDataTest, GetBoolBehaviors) {
    // Arrange
    nlohmann::json node = {
        {"is_active", true}, {"is_admin", "yes"}  // Type mismatch target
    };

    // Act & Assert
    EXPECT_TRUE(JsonHelper::get_bool(node, "is_active", false));
    EXPECT_FALSE(JsonHelper::get_bool(node, "is_verified", false));  // Missing key -> returns default
    EXPECT_TRUE(JsonHelper::get_bool(node, "is_verified", true));    // Missing key -> returns default
    EXPECT_FALSE(JsonHelper::get_bool(node, "is_admin", false));     // Type mismatch
}

/**
 * @test Test safe extraction of nested nodes (Objects and Arrays).
 */
TEST(JsonHelperDataTest, GetNodeBehaviors) {
    // Arrange
    nlohmann::json node = {{"metadata", {{"author", "Victor"}, {"year", 2026}}}, {"tags", {"cpp", "gtest"}}};

    // Act & Assert
    // Scenario A: Extract existing child object
    nlohmann::json meta = JsonHelper::get_node(node, "metadata");
    ASSERT_TRUE(meta.is_object());
    EXPECT_EQ(meta["author"].get<std::string>(), "Victor");

    // Scenario B: Extract existing child array
    nlohmann::json tags = JsonHelper::get_node(node, "tags");
    ASSERT_TRUE(tags.is_array());
    EXPECT_EQ(tags.size(), 2);

    // Scenario C: Request a missing node (Should return an empty JSON object safely)
    nlohmann::json missing_node = JsonHelper::get_node(node, "credentials");
    EXPECT_TRUE(missing_node.is_object());
    EXPECT_TRUE(missing_node.empty());
}

nlohmann::json generate_large_data(size_t count) {
    nlohmann::json root = nlohmann::json::array();

    for (size_t i = 0; i < count; ++i) {
        nlohmann::json user;
        user["id"]       = i + 1000;
        user["username"] = "user_" + std::to_string(i);
        user["meta"]     = {{"login_count", i * 5}, {"status", (i % 2 == 0) ? "active" : "offline"}};
        user["tags"]     = {"member", "dev_pool"};

        root.push_back(user);
    }

    return root;
}

// ============================================================================
// 2. UNIT TEST FOR BULK DATA GENERATION
// ============================================================================

/**
 * @test Verify generation of structured large-scale data and sample properties.
 */
TEST(JsonHelperBulkTest, GeneratesLargeDataCorrectly) {
    // 1. ARRANGE
    const size_t target_size = 1000;

    // 2. ACT: Generate 1000 structured user objects instantly in RAM
    nlohmann::json bulk_data = generate_large_data(target_size);

    // 3. ASSERT
    ASSERT_TRUE(bulk_data.is_array());
    ASSERT_EQ(bulk_data.size(), target_size);

    // Sample-check the first item to verify internal properties
    nlohmann::json first_user = bulk_data[0];
    EXPECT_EQ(first_user["id"].get<int>(), 1000);
    EXPECT_EQ(first_user["username"].get<std::string>(), "user_0");
    EXPECT_EQ(first_user["meta"]["status"].get<std::string>(), "active");

    // Sample-check the last item to verify scaling logic
    nlohmann::json last_user = bulk_data[target_size - 1];
    EXPECT_EQ(last_user["id"].get<int>(), 1999);
    EXPECT_EQ(last_user["username"].get<std::string>(), "user_999");

    JsonHelper::save_to_file("base_config.json", last_user, true);
}

bool load_base_schema(const std::string& file_path, nlohmann::json& root) {
    // Re-use our safe load function built previously
    if (!JsonHelper::load_from_file(file_path, root)) {
        return false;
    }

    // Structural validation: Ensure the base file has the critical keys we expect
    if (!root.contains("username") || !root.contains("login_count")) {
        std::cerr << "[JsonHelper] Base file validation failed: Missing vital keys." << std::endl;
        return false;
    }

    return true;
}

/**
 * @test Verify appending elements to the end, front, and middle of a JSON Array.
 */
TEST(JsonHelperMutationTest, ArrayAppendAndInsertBehaviors) {
    // 1. ARRANGE: Create a starting JSON object with a basic array
    nlohmann::json root;
    load_base_schema("base_config.json", root);
    root["languages"] = nlohmann::json::array({"C++", "Python"});

    // 2. ACT & ASSERT: Scenario A - Append to the END (Back)
    bool append_back_ok = JsonHelper::append_back(root, "languages", "Go");
    ASSERT_TRUE(append_back_ok);
    EXPECT_EQ(root["languages"].size(), 3);
    EXPECT_EQ(root["languages"].back().get<std::string>(), "Go");

    JsonHelper::save_to_file("append_back_alphabet.json", root);
    JsonHelper::save_to_file_ordered("append_back_ordered.json", root);

    // Scenario B: Append to the START (Front)
    bool append_front_ok = JsonHelper::append_front(root, "languages", "C#");
    ASSERT_TRUE(append_front_ok);
    EXPECT_EQ(root["languages"].size(), 4);
    EXPECT_EQ(root["languages"].front().get<std::string>(), "C#");  // First element should be C#

    JsonHelper::save_to_file("append_front.json", root, true);

    // Scenario C: Insert into the MIDDLE (Index 2)
    // Current layout: ["C#", "C++", "Python", "Go"]
    bool insert_mid_ok = JsonHelper::insert_at(root, "languages", 2, "Rust");
    ASSERT_TRUE(insert_mid_ok);
    EXPECT_EQ(root["languages"].size(), 5);
    EXPECT_EQ(root["languages"][2].get<std::string>(), "Rust");  // ["C#", "C++", "Rust", "Python", "Go"]

    JsonHelper::save_to_file("insert_mid.json", root, true);
}

/**
 * @test Verify error handling when passing wrong data types or out-of-bound indices.
 */
TEST(JsonHelperMutationTest, HandlesMutationErrorsGracefully) {
    // 1. ARRANGE: Set up a node containing a non-array target and a good array
    nlohmann::json root;
    root["not_an_array"] = "I am a pure string";
    root["items"]        = {"apple", "banana"};

    // 2. ACT & ASSERT: Scenario A - Trying to append to a string key (Should fail)
    bool fail_append = JsonHelper::append_back(root, "not_an_array", "orange");
    EXPECT_FALSE(fail_append) << "Should return false because target key is not a JSON Array";

    // Scenario B: Trying to insert front on a non-existent key (Should fail)
    bool fail_front = JsonHelper::append_front(root, "ghost_key", "value");
    EXPECT_FALSE(fail_front);

    // Scenario C: Inserting at an out-of-bounds index (Index 10 on a size 2 array)
    bool fail_bounds = JsonHelper::insert_at(root, "items", 10, "cherry");
    EXPECT_FALSE(fail_bounds) << "Should return false if index is larger than array size";
}

// ============================================================================
// MAIN RUNNER
// ============================================================================
int main(int argc, char** argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}