# SHELL
#shell /usr/bin/bash

# Reduces the number of trailing cells for a cleaner, less "messy" look
cursor_trail 3 

# Set a faster decay so the trail doesn't "linger" too long
# First value is min decay, second is max decay (in seconds)
cursor_trail_decay 0.1 0.99

# Set threshold to 0 so it triggers EVERY time you switch windows
cursor_trail_start_threshold 0

# MOD KEY
# kitty_mod ctrl+shift
# SPLIT WINDOWS
#map ctrl+alt+enter launch --location=split
# LAYOUT
# enabled_layouts tall,*
enabled_layouts splits
map ctrl+alt+v     launch --location=vsplit --cwd=current
map ctrl+alt+h     launch --location=hsplit --cwd=current
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right
map ctrl+k neighboring_window up
map ctrl+j neighboring_window down
#mouse_map right click ungrabbed paste_from_clipboard
mouse_map shift+right click ungrabbed no_op

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

# FONTS
font_family Hack Nerd Font
bold_font	Hack Nerd Font Bold
italic_font	Hack Nerd Font Italic
bold_italic_font	Hack Nerd Font Bold Italic

font_size 16

# TRANSPARENCY
# background_opacity 1
background_opacity 0.8
# WINDOWS
window_margin_width 1
single_window_margin_width 0
background_blur 1
# BACKGROUND
# background_image </path>
# background_image_layout scaled

# WINDOW BORDER
# active_border_color #00FFFF
# inactive_border_color #000000
# window_border_width 2pt

# BACKGROUND PHOTO
background_tint 0.90
background_tint_gaps -10

# TAB LOOK
tab_bar_style powerline
tab_powerline_style slanted
tab_activity_symbol *

# MAPPED KEYS
map F1 new_window_with_cwd
map F2 launch --cwd=current /usr/bin/vi .

# CURSSOR
# cursor #cccccc
# cursor_text_color #111111
# cursor_shape block
# cursor_shape_unfocused hollow
# cursor_beam_thickness 1.5
# cursor_blink_interval -1
# cursor_trail 0
# cursor_trail_decay 0.1 0.4
# cursor_trail_start_threshold 2
# scrollback_lines 2000
# scrollbar scrolled

# cursor_trail 10
# cursor_trail_decay 0.1 0.3
# cursor_trail_start_threshold 2

# cursor_trail_start_threshold 0
# cursor_trail 50
# cursor_trail_decay 0.2 0.4

# clear short cut of kitty
# map ctrl+a no_op

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5

xclip -selection clipboard -o | sed -r 's/\x1B\[[0-9;]*[A-Za-z]//g' | xclip -selection clipboard

