" store at ~/.vimrc
"

set nocompatible
syntax on
set number
set encoding=utf-8
set hidden
set nobackup
set nowritebackup
set cmdheight=2
set updatetime=300
set shortmess+=c

call plug#begin('~/.vim/plugged')
Plug 'vim-scripts/AutoComplPop'
call plug#end()

