name: Sync Linux Readme to Root

on:
  push:
    branches:
      - "documentation"

jobs:
  sync-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run script to merge markdown contents
      run: python sync_readme.py

    - name: Commit and Push synchronized files to GitHub
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@://github.com'
        if ! git diff --exit-code README.md; then
          git add README.md
          git commit -m "docs: sync linux documentation and fix asset paths [skip ci]"
          git push
        else
          echo "No documentation variations caught. Passing deployment phase."
        fi
