version: '3.8'

services:
  ros2_humble:
    image: osrf/ros:humble-desktop-full
    container_name: ros2_humble_container
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev:rw
      - ./workspace:/home/ros/workspace:rw
    stdin_open: true
    tty: true
    restart: unless-stopped
